/* Automatically generated by './build/bin/build-entry.js' */
const components = [
    PageEdit,
  LayerPhoto,
  LayerText
]
const install = function() {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
}
export default {
  version: '1.0.2-2',
  install,
  PageEdit,
  LayerPhoto,
  LayerText
}
